[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mixmil"
version = "0.0.1"
dependencies = []

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
